info:
  profile: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/


#database ,jpa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big-world?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

