info:
  profile: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/


#database ,jpa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big-world?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

#忽略权限拦截
management:
  security:
    enabled:  false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  30000  #缺省为1000


security:
  user:
    name: admin
    password: admin
    role: USER
  basic:
    enabled: false

mybatis:
  basepackage: com.wxq.bigworld.clientuser.web.mapper
  xmlLocation: classpath:mappings/**/*.xml