info:
  profile: default

spring:
  redis:
    host: localhost
    database: 7
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 0
      max-wait: -1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/


feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000



#bigworld配置
bigworld:
  jwt:
    secret: defaultSecret     # JWT签名密钥，默认为defaultSecret
    expiration: 3600          # JWT过期时间（秒），默认为3600s，一小时
    md5Key: randomKey         # md5Key，每个token都对应一个唯一的md5key，默认值为randomKey
    autoRefreshTokenExpiration: 60  # 判断token还剩余多少秒到期后自动刷新Token，并放到header里。默认是60s， -1为不刷新。
    preventsLogin: false      # 判断是否开启允许多人同账号同时在线，若不允许的话则将上一个人T掉，默认false，不T掉，允许多人登录，true：T掉
  security:
    authorize:
      permitUrls: /register ,/login   #不需要认证的页面 逗号隔开
