info:
  profile: default

spring:
  redis:
    host: localhost
    database: 7
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 0
      max-wait: -1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/


feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000