spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/im-Luxqi/Bigworld-All
          searchPaths: bigworld-config/configFile
server:
    port: 9999