spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/im-Luxqi/bigworld-configcenter
          searchPaths: repos/bigworld
server:
    port: 9999